// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/demo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CasoRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	InfectedType         string   `protobuf:"bytes,4,opt,name=infected_type,json=infectedType,proto3" json:"infected_type,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CasoRequest) Reset()         { *m = CasoRequest{} }
func (m *CasoRequest) String() string { return proto.CompactTextString(m) }
func (*CasoRequest) ProtoMessage()    {}
func (*CasoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{0}
}

func (m *CasoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CasoRequest.Unmarshal(m, b)
}
func (m *CasoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CasoRequest.Marshal(b, m, deterministic)
}
func (m *CasoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CasoRequest.Merge(m, src)
}
func (m *CasoRequest) XXX_Size() int {
	return xxx_messageInfo_CasoRequest.Size(m)
}
func (m *CasoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CasoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CasoRequest proto.InternalMessageInfo

func (m *CasoRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CasoRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *CasoRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CasoRequest) GetInfectedType() string {
	if m != nil {
		return m.InfectedType
	}
	return ""
}

func (m *CasoRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type Reply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{2}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CasoReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	InfectedType         string   `protobuf:"bytes,4,opt,name=infected_type,json=infectedType,proto3" json:"infected_type,omitempty"`
	State                string   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CasoReply) Reset()         { *m = CasoReply{} }
func (m *CasoReply) String() string { return proto.CompactTextString(m) }
func (*CasoReply) ProtoMessage()    {}
func (*CasoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10b39337e838aa, []int{3}
}

func (m *CasoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CasoReply.Unmarshal(m, b)
}
func (m *CasoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CasoReply.Marshal(b, m, deterministic)
}
func (m *CasoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CasoReply.Merge(m, src)
}
func (m *CasoReply) XXX_Size() int {
	return xxx_messageInfo_CasoReply.Size(m)
}
func (m *CasoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CasoReply.DiscardUnknown(m)
}

var xxx_messageInfo_CasoReply proto.InternalMessageInfo

func (m *CasoReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CasoReply) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *CasoReply) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CasoReply) GetInfectedType() string {
	if m != nil {
		return m.InfectedType
	}
	return ""
}

func (m *CasoReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*CasoRequest)(nil), "grpc.CasoRequest")
	proto.RegisterType((*Reply)(nil), "grpc.Reply")
	proto.RegisterType((*Empty)(nil), "grpc.Empty")
	proto.RegisterType((*CasoReply)(nil), "grpc.CasoReply")
}

func init() { proto.RegisterFile("proto/demo.proto", fileDescriptor_bf10b39337e838aa) }

var fileDescriptor_bf10b39337e838aa = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0xff, 0xad, 0x29, 0x9d, 0x82, 0x28, 0x16, 0x0b, 0xab, 0xab, 0x12, 0x36, 0x15,
	0xd0, 0x04, 0xc1, 0x09, 0x00, 0xb1, 0x63, 0x15, 0xb1, 0x62, 0x83, 0xdc, 0x64, 0x48, 0x2d, 0xe2,
	0xd8, 0xc4, 0x53, 0xa1, 0xdc, 0x00, 0x71, 0x6a, 0x64, 0x87, 0xa2, 0xde, 0x80, 0x95, 0xdf, 0xbc,
	0x99, 0x67, 0x7d, 0x1e, 0xc3, 0xd4, 0xb5, 0x96, 0x6c, 0x56, 0xa2, 0xb1, 0x69, 0x94, 0x62, 0x58,
	0xb5, 0xae, 0x48, 0xbe, 0x18, 0x4c, 0xee, 0x95, 0xb7, 0x39, 0xbe, 0x6f, 0xd0, 0x93, 0x10, 0x30,
	0x6c, 0x94, 0x41, 0xc9, 0xe6, 0x6c, 0x31, 0xce, 0xa3, 0x16, 0x33, 0xd8, 0xaf, 0x6d, 0xa1, 0x48,
	0xdb, 0x46, 0xfe, 0x8f, 0xfe, 0x6f, 0x2d, 0xa6, 0x30, 0x50, 0x15, 0xca, 0xc1, 0x9c, 0x2d, 0x78,
	0x1e, 0xa4, 0x38, 0x83, 0x43, 0xdd, 0xbc, 0x62, 0x41, 0x58, 0xbe, 0x50, 0xe7, 0x50, 0x0e, 0x63,
	0xe4, 0x60, 0x6b, 0x3e, 0x75, 0x0e, 0xc5, 0x09, 0x70, 0x4f, 0x8a, 0x50, 0xf2, 0xd8, 0xec, 0x8b,
	0xe4, 0x14, 0x78, 0x8e, 0xae, 0xee, 0x84, 0x84, 0x91, 0x41, 0xef, 0xc3, 0xcd, 0x3d, 0xc8, 0xb6,
	0x4c, 0x46, 0xc0, 0x1f, 0x8c, 0xa3, 0x2e, 0xf9, 0x64, 0x30, 0xee, 0xc1, 0x43, 0xe0, 0x2f, 0xb1,
	0xaf, 0x11, 0x78, 0x20, 0xf1, 0xe2, 0x02, 0x46, 0xb7, 0x65, 0x19, 0xb4, 0x38, 0x4e, 0xc3, 0x7a,
	0xd3, 0x9d, 0xd5, 0xce, 0x26, 0xbd, 0x15, 0x81, 0x93, 0x7f, 0x22, 0x83, 0xc9, 0xa3, 0xf6, 0xa4,
	0xda, 0x3e, 0xfb, 0xd3, 0x8d, 0x8f, 0x9b, 0x1d, 0xed, 0xa6, 0xe3, 0xf8, 0x15, 0xbb, 0xbb, 0x7c,
	0x3e, 0xaf, 0x34, 0xad, 0x37, 0xab, 0xb4, 0xb0, 0x26, 0x23, 0x6b, 0xb4, 0x7d, 0xcb, 0xc2, 0xdc,
	0x92, 0xd0, 0xd3, 0xf2, 0x43, 0xfb, 0x75, 0xad, 0x3d, 0x65, 0xf1, 0x7b, 0x57, 0x7b, 0xf1, 0xb8,
	0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x62, 0x8a, 0xa1, 0xf3, 0xf9, 0x01, 0x00, 0x00,
}
